{% set name = "qcelemental" %}
{% set version = "0.2.1" %}
{% set sha256 = "85355a1b15ac47856804577d154e122c45c3a09561fb5892352106b08f24f13c" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/MolSSI/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
    host:
        - python
        - pip
    run:
        - numpy
        - pint
        - pydantic >=0.18.*
        - python

test:
    imports:
        - qcelemental
    requires:
        - deepdiff
        - pytest
    commands:
        - pytest --pyargs qcelemental

about:
    home: https://github.com/MolSSI/QCElemental
    dev_url: https://github.com/MolSSI/QCElemental
    doc_url: https://qcelemental.readthedocs.io/en/latest/
    doc_source_url: https://github.com/MolSSI/QCElemental/blob/master/docs/source/index.rst
    license: BSD-3-Clause
    license_url: https://opensource.org/licenses/BSD-3-Clause
    license_file: LICENSE
    license_family: BSD
    summary: QCElemental is a resource module for quantum chemistry containing physical constants and periodic table data from NIST and molecule handlers.

extra:
    recipe-maintainers:
        - loriab
        - dgasmith
